### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by Patel135** [margaretmz/selfie2anime-with-tflite#1]
Getting this error while importing
- This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.1 or newer.

My studio version specification
- Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4

Can you please suggest me how can i resolves this error?

**Comment by krllus** [comment]
you need to update your android version studio to the beta or canary versions, please refer to this link
https://developer.android.com/studio/preview
