### ISSUE TITLE
Issue with Model or Me?

### ISSUE THREAD

**Issue by GantMan** [margaretmz/selfie2anime-with-tflite#2]
Updated to Beta, virtualized my webcam and rotated it and finally got it to run, but the result seems like I might have made a mistake somewhere?  Is there a known issue, or is this the general performance of the model?

![image](https://user-images.githubusercontent.com/997157/89131982-789f0a00-d4d6-11ea-9a71-b017e19d9703.png)

**Comment by sayakpaul** [comment]
Sorry for being late. As we point out in the tutorial that this is a known issue. The poor results are stemming from the fact that the model was trained a specific set of faces so it fails to generalize well to faces that are not in that set.
